name: Generate documentation

on:
  workflow_dispatch:

jobs:
  generate:
    name: Generate
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: update-access-profile # TODO: set branch to dev

      - name: Setup Git
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Generate documentation
        run: go generate
        shell: bash

      - name: Commit
        shell: bash
        run: |
          git add -A
          git commit -m "docs: update generated documentation"

      - name: Push
        shell: bash
        run: git push
